env:
  browser: true
  es2021: true
  'jest/globals': true
extends:
  - 'standard-with-typescript'
  - 'plugin:jest/recommended'
  - 'plugin:jest/style'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {}
root: true